name: on_the_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bobby Jones
      fonts:
        - asset: assets/fonts/Bobby Rough Soft Outline.ttf
        - asset: assets/fonts/Bobby Rough Soft.ttf
  assets:
    - lib/assets/profile_pictures/
    - lib/assets/fonts/
